import can1 from "../assests/products/can-1.png"
import can2 from "../assests/products/can-2.png"
import egg1 from "../assests/products/egg-1.png"
import egg2 from "../assests/products/egg-2.png"
import meat1 from "../assests/products/beef.png"
import meat2 from "../assests/products/fish.png"
import fruit1 from "../assests/products/banana.png"
import fruit2 from "../assests/products/apple.png"

export const products = [
    {
        id: 1,
        category: "beverages",
        title: "Diet Coke",
        description: "Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.",
        image: can1,
        price: 10,
        amount: "335ml",
        nutritions: 100,
        cartQuantity: 1,
    },
    {
        id: 2,
        category: "beverages",
        title: "black Coke",
        description: "Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.",
        image: can2,
        price: 22,
        amount: "335ml",
        nutritions: 100,
        cartQuantity: 1,
    },
    {
        id: 3,
        category: "beverages",
        title: "soda Coke",
        description: "Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.",
        image: can1,
        price: 100,
        amount: "335ml",
        nutritions: 100,
        cartQuantity: 1,
    },
    {
        id: 4,
        category: "beverages",
        title: "orange juice",
        description: "Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.",
        image: can2,
        price: 50,
        amount: "335ml",
        nutritions: 100,
        cartQuantity: 1,
    },
    {
        id: 5,
        category: "eggs",
        title: "Egg Chicken Red",
        description: "Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.",
        image: egg1,
        price: 10,
        amount: "4pcs",
        nutritions: 100,
        cartQuantity: 1,
    },
    {
        id: 6,
        category: "eggs",
        title: "Egg Chicken White",
        description: "Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.",
        image: egg2,
        price: 55,
        amount: "2pcs",
        nutritions: 100,
        cartQuantity: 1,
    },
    {
        id: 7,
        category: "eggs",
        title: "Egg Pasta ",
        description: "Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.",
        image: egg1,
        price: 100,
        amount: "9pcs",
        nutritions: 100,
        cartQuantity: 1,
    },
    {
        id: 8,
        category: "eggs",
        title: "Egg Noodles",
        description: "Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.",
        image: egg2,
        price: 55,
        amount: "3pcs",
        nutritions: 100,
        cartQuantity: 1,
    },
    {
        id: 9,
        category: "meat & fish",
        title: "Beef Bone",
        description: "Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.",
        image: meat1,
        price: 44,
        amount: "3kg",
        nutritions: 100,
        cartQuantity: 1,
    },
    {
        id: 10,
        category: "meat & fish",
        title: "Meat Lamb",
        description: "Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.",
        image: meat2,
        price: 52,
        amount: "1pcs",
        nutritions: 100,
        cartQuantity: 1,
    },
    {
        id: 11,
        category: "meat & fish",
        title: "Shrimp",
        description: "Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.",
        image: meat1,
        price: 22,
        amount: "2kg",
        nutritions: 100,
        cartQuantity: 1,
    },
    {
        id: 12,
        category: "meat & fish",
        title: "Fish",
        description: "Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.",
        image: meat2,
        price: 10,
        amount: "2pcs",
        nutritions: 100,
        cartQuantity: 1,
    },
    {
        id: 13,
        category: "Fresh Fruits & Vegetable",
        title: "Red Apple",
        description: "Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.",
        image: fruit1,
        price: 54,
        amount: "1kg",
        nutritions: 100,
        cartQuantity: 1,
    },
    {
        id: 14,
        category: "Fresh Fruits & Vegetable",
        title: "Organic Bananas",
        description: "Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.",
        image: fruit2,
        price: 21,
        amount: "4kg",
        nutritions: 100,
        cartQuantity: 1,
    },
    {
        id: 15,
        category: "Fresh Fruits & Vegetable",
        title: "Bell Pepper Red",
        description: "Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.",
        image: fruit1,
        price: 63,
        amount: "3kg",
        nutritions: 100,
        cartQuantity: 1,
    },
    {
        id: 16,
        category: "Fresh Fruits & Vegetable",
        title: "Ginger",
        description: "Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.",
        image: fruit2,
        price: 45,
        amount: "2kg",
        nutritions: 100,
        cartQuantity: 1,
    },
]
export const cateogries = [
    {
        id: 1,
        title: "beverages",
        image: can1,
        color: "83, 177, 117",
    },
    {
        id: 2,
        title: "eggs",
        image: egg1,
        color: "248, 164, 76",
    },
    {
        id: 3,
        title: "meat & fish",
        image: meat1,
        color: "247, 165, 147",
    },
    {
        id: 4,
        title: "Fresh Fruits & Vegetable",
        image: fruit1,
        color: "211, 176, 224",
    },
]